package ba.telegroup.university_system.controller;

import ba.telegroup.university_system.common.exception.BadRequestException;
import ba.telegroup.university_system.model.User;
import ba.telegroup.university_system.repository.UserRepository;
import ba.telegroup.university_system.util.Notificatioin;
import ba.telegroup.university_system.util.SHA512;
import net.bytebuddy.utility.RandomString;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.http.HttpStatus;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;
import java.security.NoSuchAlgorithmException;
import java.util.List;
import java.util.Map;

@RestController
@RequestMapping("/hub/user")
@Scope("request")
public class UserController {
    private final UserRepository userRepository;
    private final Notificatioin notificatioin;

    @PersistenceContext
    private EntityManager entityManager;

    @Autowired
    public UserController(UserRepository userRepository, Notificatioin notificatioin) {
        this.userRepository = userRepository;
        this.notificatioin = notificatioin;
    }

    @GetMapping(value = "/")
    public List<User> getAll() {
        return userRepository.getAllByActive((byte) 1);
    }

    @GetMapping(value = "/{id}")
    public User getById(@PathVariable Integer id) {
        return userRepository.getById(id);
    }

    @Transactional
    @PostMapping(value = "/")
    @ResponseStatus(HttpStatus.CREATED)
    public User insert(@RequestBody User user) throws NoSuchAlgorithmException, BadRequestException {
        String autoGenerated = RandomString.make(8);
        user.setPassword(autoGenerated);
        String mailBody = "Poštovani,<br><br>Vaša lozinka za aplikaciju <b>University System</b> je <b>" + user.getPassword() + "</b>, a korisničko ime je <b>" + user.getUsername() + "</b>.<br>";
        user.setPassword(SHA512.getSHA512(autoGenerated));

        User insertedUser = userRepository.saveAndFlush(user);
        if (insertedUser != null) {
            entityManager.refresh(insertedUser);
            System.out.println(mailBody);
            return insertedUser;
        } else
            return null;
    }

    @Transactional
    @PutMapping(value = "/")
    public User update(@RequestBody User user) {
        if (userRepository.getById(user.getId()) != null) {
            user.setActive((byte) 1);
            User updatedUser = userRepository.saveAndFlush(user);
            entityManager.refresh(updatedUser);
            return updatedUser;
        }
        return null;
    }

    @DeleteMapping(value = "/{id}")
    public String delete(@PathVariable Integer id) {
        User user = userRepository.getById(id);
        if (user != null) {
            user.setActive((byte) 0);
            userRepository.saveAndFlush(user);
            return "Success";
        } else
            return "Fail";

    }



    @SuppressWarnings("SameReturnValue")
    @GetMapping(value = "/logout")
    public @ResponseBody
    String logout(HttpServletRequest request) {
        HttpSession session = request.getSession(false);
        if (session != null) {
            session.invalidate();
        }

        return "Success";
    }

    @PutMapping(value = "/changePassword")
    public String changePassword(@RequestBody Map<String, String> userMap) throws NoSuchAlgorithmException {
        User user = userRepository.getByIdAndPassword(Integer.parseInt(userMap.get("id")), SHA512.getSHA512(userMap.get("currentPassword")));
        if (user != null) {
            if (!userMap.get("currentPassword").equals(userMap.get("password"))) {
                String newPassSha512 = SHA512.getSHA512(userMap.get("password"));
                if (!user.getPassword().equals(newPassSha512)) {
                    user.setPassword(newPassSha512);
                    if (userRepository.changePassword(user) > 0) {
                        return "Success";
                    } else
                        return "Fail";
                } else
                    return "Fail";
            } else
                return "Fail";
        } else
            return "Fail";
    }


}
